### ISSUE TITLE
why is it deprecated?

### ISSUE THREAD

**Issue by Profpatsch** [jwiegley/rehoo#2]
Is there a replacement for `rehoo`. Does hoogle support the functionality now?

Update: It looks like hoogle 5 isn’t able to combine `.hoo` databases. Hrm.

**Comment by jwiegley** [comment]
I think `Hoogle 5` needs some work still to support the same use cases as `Hoogle 4`.  For now, Nix has regressed back to 4 because of this, for example.

**Comment by Profpatsch** [comment]
Yes, I was the one that made the change. :)
But it looks like the guys fixed it by patching hoogle so it can create one binary file from multiple inputs, rendering the binary concatenation unnecessary.

**Comment by jwiegley** [comment]
@Profpatsch Ah, thanks for that!  I'm now using your change [in my DockerHub image](https://hub.docker.com/r/jwiegley/hoogle-local/) that provides a fully-loaded local Hoogle.

I'll be glad when I can abandon this project, and cross one more thing off the todo list. :)
